
version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:5000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
    depends_on:
      - redis

  redis:
    image: "redis:6-alpine"

    volumes:
      - redis_data:/data

volumes:
  redis_data: